COMMENT=		"web page monitoring software"

DISTNAME=		websec-1.8.0	
CATEGORIES=		www	

HOMEPAGE=		http://baruch.ev-en.org/proj/websec/			

MAINTAINER=		Thomas Delaet <thomas@delaet.org>	

# GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=		http://savannah.nongnu.org/download/websec/	
USE_GMAKE=		Yes

.include <bsd.port.mk>
